name: cordless
version: git
summary: Third party discord client
description: |
  A third party discord client for your terminal.

confinement: strict
grade: stable
architectures:
  - amd64
base: core18

parts:
  cordless:
    plugin: go
    go-channel: 1.14/stable
    go-importpath: github.com/Bios-Marcel/cordless
    source: .
    source-type: git
    stage-packages:
      - xclip
      - libnotify-bin
    build-packages:
      - gcc
      - libc6-dev

apps:
  cordless:
    command: bin/cordless
    plugs: [x11, network-bind, desktop]
    environment:
      XDG_CONFIG_HOME: $SNAP_USER_DATA/